# Generated by Django 6.0.1 on 2026-01-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_mpesarequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesarequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
