# Generated by Django 6.0 on 2026-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('DIGITAL', 'Digital'), ('SAVINGS', 'Savings')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('overspend_rule', models.CharField(choices=[('BLOCK', 'Block'), ('WARN', 'Warn'), ('ALLOW', 'Allow')], default='BLOCK', max_length=10)),
                ('rollover_rule', models.CharField(choices=[('ROLLOVER', 'Rollover'), ('RETURN', 'Return'), ('REALLOCATE', 'Reallocate')], default='ROLLOVER', max_length=15)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
