# Generated by Django 6.0.1 on 2026-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='last_applied',
            field=models.DateField(blank=True, null=True),
        ),
    ]
